### ISSUE TITLE
New architecture

### ISSUE THREAD

**Issue by petewall** [petewall/eink-radiator#180]
Re-architect everything to be more micro-service-y. This will make the development process easier. It will also allow for plugin-style image development.

Instead of one monolithic code base, split into multiples:

1. `eink-radiator` is the coordinator
2. Each image source becomes a single cli. Input a config, output an image, using a standardized UI
3. New project: `eink-radiator-display`: takes an image and sends to the actual display. This one has to be Python because [inky](https://github.com/pimoroni/inky) is.
4. New project: `eink-radiator-ui` is the graphical representation and interface

The OS image will need to have [vendir](https://carvel.dev/vendir/). An os startup script will use that to download the latest release of eink-radiator and the image sources. There config files that will be persisted on the device:

`screen.yaml`:
```yaml
size:
  height: 480
  width: 640
palette:
- RED
- WHITE
- BLACK
path: eink-radiator-display
```

`data.yaml` (or a better name):
```yaml
rotation:
- name: Family
  type: eink-radiator-image
  params:
    scale: contain
    url: http://example.com/images/family.png
    background_color: WHITE
    transform: none
- type: delay
  params:
    duration: 5000
interrupts: {}  # To be populated later by plugins that can interrupt the normal flow. This allows for "notification"-style screens
```

The `eink-radiator` process will use both config files to handle the scheduling of various screen content. When it's time to draw a new screen, the content CLI will be executed with the screen.yaml and just the section for that content, then sending that to the screen cli. Essentially doing this:

```bash
eink-radiator-image -s screen.yaml -c config.yaml > image.png
eink-radiator-display -s screen.yaml -i image.png
```
