### ISSUE TITLE
New image type: QR code

### ISSUE THREAD

**Issue by petewall** [petewall/eink-radiator#182]
Take text and export as QR code

```yaml
name: qr-code-test
type: eink-radiator-qr-code
params:
  text: "this is the text to be encoded"
```
