### ISSUE TITLE
New image type: stocks

### ISSUE THREAD

**Issue by petewall** [petewall/eink-radiator#183]
Two potential image sources:

single stock: Show the trend line for a stock over a time period. Goes red when price is down. Shows symbol, name, price, etc...
```yaml
name: goog
type: eink-radiator-stock
params:
  symbol: GOOG
  range: 1M
```

stocks: Shows multiple stocks in table format
```yaml
name: stocks
type: eink-radiator-stocks
params:
  symbols:
  - GOOG
  - VMW
  - AAPL
```
